# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ç½‘æ˜“äº‘éŸ³ä¹

on:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_updateCFD
jobs:
  build:
    env:
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # æˆ‘è‡ªå·±åŒæ­¥åˆ°giteeä½¿ç”¨ï¼Œå…¶ä»–äººå¯å¿½ç•¥
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: 'è¿è¡Œ ã€ç½‘æ˜“äº‘éŸ³ä¹ã€‘'
        run: |
          node scripts/netease_music/neteasemusic.js
        env:
          NETEASE_COOKIE: ${{ secrets.NETEASE_COOKIE }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
      - name: commit
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git add .
          git commit -m "update by Github Action" -a || echo "Nothing to update"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
          
      # å•ä¸€ä»“åº“å†…å®¹å†…å®¹åŒæ­¥åˆ°è‡ªå·±çš„giteeä¸Š
      - name: å¼€å§‹åŒæ­¥ã€DailyActionsã€‘ä»“åº“ğŸ”„
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/h455257166
          dst: gitee/h455257166
          static_list: "DailyActions"
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          debug: true